packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"

allowBuilds:
  bufferutil: true
  core-js: true
  esbuild: true
  sharp: true
  utf-8-validate: true

catalog:
  zod: ^3.25.76
  react: ^19.0.0
  react-dom: ^19.0.0
  "@types/react": ^19.0.10
  "@types/react-dom": ^19.0.10
  "@types/node": ^22.13.10
  typescript: ^5.9.2

minimumReleaseAgeExclude:
  - convex@1.42.2
