contact_links:
    - name: Ask a question
      url: https://github.com/Zed-Softworks-Official/nemu/discussions
      about: Ask questions and discuss with other community members
    - name: Feature request
      url: https://github.com/Zed-Softworks-Official/nemu/discussions/new?category=ideas
      about: Feature requests should be opened as discussions
